/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Control;

/**
 *
 * @author ingenieria
 */
public class Principal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonMod4 = new javax.swing.JButton();
        jButtonMod1 = new javax.swing.JButton();
        jButtonMod2 = new javax.swing.JButton();
        jButtonMod5 = new javax.swing.JButton();
        jButtonMod3 = new javax.swing.JButton();

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jButtonMod4.setText("Ingresar lista de recetas y ordenar");
        jButtonMod4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMod4ActionPerformed(evt);
            }
        });

        jButtonMod1.setText("Crear Receta");
        jButtonMod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMod1ActionPerformed(evt);
            }
        });

        jButtonMod2.setText("Buscar por Nombre o tiempo de cocción");
        jButtonMod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMod2ActionPerformed(evt);
            }
        });

        jButtonMod5.setText("Buscar y detalles receta");
        jButtonMod5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMod5ActionPerformed(evt);
            }
        });

        jButtonMod3.setText("Buscar por Lista de Ingredientes");
        jButtonMod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMod3ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jButtonMod4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonMod1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonMod2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonMod5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonMod3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMod1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMod2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jButtonMod3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMod4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMod5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonMod1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMod2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMod3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMod4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMod5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMod4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMod4ActionPerformed
        // TODO add your handling code here:
        
        ListaReceta LiRe = new ListaReceta();
        jDesktopPane1.add(LiRe);
        LiRe.setVisible(true);
    }//GEN-LAST:event_jButtonMod4ActionPerformed

    private void jButtonMod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMod1ActionPerformed
        // TODO add your handling code here:
        NuevaReceta NuRe = new NuevaReceta();
        jDesktopPane1.add(NuRe);
        NuRe.setVisible(true);
    }//GEN-LAST:event_jButtonMod1ActionPerformed

    private void jButtonMod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMod2ActionPerformed
        // TODO add your handling code here:
        BuscarNombreOTiempo NoTi = new BuscarNombreOTiempo();
        jDesktopPane1.add(NoTi);
        NoTi.setVisible(true);
    }//GEN-LAST:event_jButtonMod2ActionPerformed

    private void jButtonMod5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMod5ActionPerformed
        // TODO add your handling code here:
        BuscarYDetalles BuDe = new BuscarYDetalles();
        jDesktopPane1.add(BuDe);
        BuDe.setVisible(true);
    }//GEN-LAST:event_jButtonMod5ActionPerformed

    private void jButtonMod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMod3ActionPerformed
        // TODO add your handling code here:
        BuscarPorIngredientes BuIn = new BuscarPorIngredientes ();
        jDesktopPane1.add(BuIn);
        BuIn.setVisible(true);
    }//GEN-LAST:event_jButtonMod3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMod1;
    private javax.swing.JButton jButtonMod2;
    private javax.swing.JButton jButtonMod3;
    private javax.swing.JButton jButtonMod4;
    private javax.swing.JButton jButtonMod5;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
